### PR TITLE
Add vpx support in av1an

### PR DESCRIPTION
**Pull request by Uranite**
add support for vp8 and vp9 encoding in av1an

### CODE REVIEW

**Comment by Uranite** [comment]
Downloading from the site is really slow with wget. 7zr is slow, mkvtoolnix is slow, and now theres vpx which is also slow.
Maybe we should use something other than wget

**Comment by Hishiro64** [comment]
Switching to something other than wget can make it faster. Like aria2c for example. The fastest way would probably be to download multiple at a time. 

On a side note, `lsmas` and `ffms2` seems to no longer download. 
Not sure if it's just on my side, but I do remember it working 2 weeks ago. 
You can see if you have these errors if you remove `@echo off` at the beginning and ` > nul` on these lines.

```batch
C:\Users\test\av1an-win-script-main\dependencies\vapoursynth64>.\python.exe .\vsrepo.py update -p
Local definitions updated to: Tue, 18 Jun 2024 20:55:07 GMT

C:\Users\test\av1an-win-script-main\dependencies\vapoursynth64>.\python.exe .\vsrepo.py install lsmas ffms2 -p
Rebuilding dist-info dirs for other python package installers
Failed to download LSMASHSource 1194.0.0.0, skipping installation and moving on
Failed to download FFmpegSource2 5.0, skipping installation and moving on
Updating VapourSynth stubs
Nothing done
2 packages failed
```
I pretty sure it's unrelated to your past PRs through.

**Comment by pat-e** [comment]
I would suggest switching to "bestsource" (vsrepo install bestsource). I've seen the switch on certain Linux-applications because of problems with lsmash. Luckily, Av1an supports bestsource, so the parameters-file must be changed to add "-m bestsource" or "--chunk-method bestsource".

**Comment by Uranite** [comment]
> On a side note, lsmas and ffms2 seems to no longer download.
> Not sure if it's just on my side, but I do remember it working 2 weeks ago.
> You can see if you have these errors if you remove @echo off at the beginning and  > nul on these lines.

They're downloading just fine to me
```
>.\python.exe .\vsrepo.py install lsmas ffms2 -p

Rebuilding dist-info dirs for other python package installers
Fetching: https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/releases/download/1194.0.0.0/L-SMASH-Works-r1194.0.0.0.7z
Successfully installed LSMASHSource 1194.0.0.0
Fetching: https://github.com/FFMS/ffms2/releases/download/5.0/ffms2-5.0-msvc.7z
Successfully installed FFmpegSource2 5.0
Updating VapourSynth stubs
2 packages installed
```

**Comment by pat-e** [comment]
Yes, but it would not hurt to add "bestsource" in the current install.bat as additional option for VapourSynth and Av1an.

**Pull request merged**
